# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install and build'
- task: AzureMysqlDeployment@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(221386e0-e9da-49fa-b7aa-96d033ab0c0f)'
    ServerName: 'aanvy.database.windows.net'
    DatabaseName: 'Aanvy'
    SqlUsername: 'aanvy'
    SqlPassword: 'Rama@722'
    TaskNameSelector: 'SqlTaskFile'
    IpDetectionMethod: 'AutoDetect'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
